Models/ErrorViewModel.cs
using System;

namespace Init.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/InfoModel.cs
namespace Init.Models
{
    public class Info 
    {
        public string Cargo { get; set; }
        public string Estudo1 { get; set; }
        public string Estudo2 { get; set; }
        public string Estudo3 { get; set; }
        public string Estudo4 { get; set; }
        public string Estudo5 { get; set; }
        public string Estágio { get; set; }
    }
}

Models/PessoaModel.cs
namespace Init.Models
{
    public class Pessoa 
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    }
}

Models/PortfolioModel.cs
namespace Init.Models
{
    public class Portfolio 
    {
        public string Git { get; set; }
        public string Bit { get; set; }
    }
}

Models/SobreModel.cs
namespace Init.Models
{
    public class Sobre 
    {
        public string Sabe1 { get; set; }
        public string Sabe2 { get; set; }
        public string Sabe3 { get; set; }
        public string Sabe4 { get; set; }
        public string Sabe5 { get; set; }
        public string Sabe6 { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Init.Models;

namespace Init.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Init.Models; 

namespace Init.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult Index()
        {
            Info info1 = new Info()
            {
                Cargo = "desenvolvedora full-stack",
                Estudo1 = "Ensino Fundamental concluído",
                Estudo2 = "Ensino Médio concluído",
                Estudo3 = "Técnico em Informática na IENH",
                Estudo4 = "Curso de desenvolvimento Full-Stack na GrowDev",
                Estudo5 = "Inglês Básico na Wizard",
                Estágio = "Estagiária na empresa BCS automação",
            };

            return View(info1);
        }
    }
}

Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using Init.Models;

namespace Init.Controllers
{
    public class PessoaController : Controller
    {
        public IActionResult Index()
        {
            Pessoa pessoa1 = new Pessoa()
            {
                Id = 1,
                Nome= "Eduarda Brisch Dalmas",
                CPF = "041.985.790-75",
                Telefone = "51 999002828",
                Email = "eduardadalmas@ienh.com.br",
            };

            return View(pessoa1);
        }
    }
}

Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Mvc;
using Init.Models; 

namespace Init.Controllers
{
    public class PortfolioController : Controller
    {
        public IActionResult Index()
        {
            Portfolio portfolio1 = new Portfolio()
            {
                Git = "https://github.com/EduardaDalmas",
                Bit= "https://bitbucket.org/EduardaDalmas/profile/repositories",
            };

            return View(portfolio1);
        }
    }
}

Controllers/SobreController.cs
using Microsoft.AspNetCore.Mvc;
using Init.Models; 

namespace Init.Controllers
{
    public class SobreController : Controller
    {
        public IActionResult Index()
        {
            Sobre sobre1 = new Sobre()
            {
                Sabe1 = "Javascript ",
                Sabe2= "HTML5/Css",
                Sabe3 = "C#",
                Sabe4 = "Node",
                Sabe5 = "React",
                Sabe6 = "MySQL/Postgree",
            };

            return View(sobre1);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Profissional Curriculum</h1>
    <p>Site profissional com informações relevantes sobre Eduarda Dalmas</a>.</p>
</div>

Views/Info/Index.cshtml
@model Init.Models.Info

@{
    ViewData["Title"] = "Info";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
    <h2> Educação </h2>
    <li>Ensino: @Model.Estudo1</li>
    <li>Ensino: @Model.Estudo2</li>
    <li>Ensino: @Model.Estudo3</li>
    <li>Ensino: @Model.Estudo4</li>
    <li>Ensino: @Model.Estudo5</li>
    <li>Estágio: @Model.Estágio</li>
</div>

Views/Pessoa/Index.cshtml
@model Init.Models.Pessoa

@{
    ViewData["Title"] = "Pessoa";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="/img/foto.jpg" height="400px" width="400"/>
        </div>
        <div class="col-md-6">
            <h2>Dados Pessoais</h2>
            <ul>
                <li>Nome:  @Model.Nome</li>
                <li>Id: @Model.Id</li>
                <li>CPF:  @Model.CPF</li>
                <li>Telefone: @Model.Telefone</li>
                <li>Email: @Model.Email</li>
            </ul>
        </div>
    </div>
</div>

Views/Portfolio/Index.cshtml
@model Init.Models.Portfolio

@{
    ViewData["Title"] = "Portfolio";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
        <ul>
            <h2>Perfis com Portfolio disponível: </h2>
            <li> Perfil no GitHub: @Model.Git</li>
            <li> Perfil no Bitbucket: @Model.Bit</li>
        </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Init</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Init</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sobre" asp-action="Index">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Index">Informações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Portfolio" asp-action="Index">Portfolio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Init - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Sobre/Index.cshtml
@model Init.Models.Sobre

@{
    ViewData["Title"] = "Sobre";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
        <ul>
            <h2>Conhecimento de: </h2>
            <li>  @Model.Sabe1</li>
            <li>  @Model.Sabe2</li>
            <li>  @Model.Sabe3</li>
            <li>  @Model.Sabe4</li>
            <li>  @Model.Sabe5</li>
            <li>  @Model.Sabe6</li>
        </ul>
</div>